org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m
org.gradle.java.home=/tmp/jdk-17.0.13+11/Contents/Home
android.useAndroidX=true
android.enableJetifier=true
android.nativeBuildOptions.pageSize=0x4000
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
