class TourPackage {
  final String id;
  final String title;
  final String destination;
  final String description;
  final String imageUrl;
  final int price;
  final int originalPrice;
  final int nights;
  final int days;
  final String category; // domestic | international | honeymoon | heritage | adventure | beach | nature
  final List<String> highlights;
  final double rating;
  final int reviews;
  final bool isFeatured;
  final String? badge;
  final String? slug;

  const TourPackage({
    required this.id,
    required this.title,
    required this.destination,
    required this.description,
    required this.imageUrl,
    required this.price,
    required this.originalPrice,
    required this.nights,
    required this.days,
    required this.category,
    required this.highlights,
    required this.rating,
    required this.reviews,
    this.isFeatured = false,
    this.badge,
    this.slug,
  });

  factory TourPackage.fromJson(Map<String, dynamic> j) => TourPackage(
        id: j['_id'] ?? j['id'] ?? '',
        title: j['title'] ?? '',
        destination: j['destination'] ?? j['location'] ?? '',
        description: j['description'] ?? '',
        imageUrl: j['imageUrl'] ?? j['image'] ?? '',
        price: (j['price'] ?? 0).toInt(),
        originalPrice: (j['originalPrice'] ?? j['price'] ?? 0).toInt(),
        nights: (j['nights'] ?? j['duration'] ?? 3).toInt(),
        days: (j['days'] ?? (j['nights'] ?? 3) + 1).toInt(),
        category: j['category'] ?? 'domestic',
        highlights: (j['highlights'] as List<dynamic>?)
                ?.map((e) => e.toString())
                .toList() ??
            [],
        rating: (j['rating'] ?? 4.5).toDouble(),
        reviews: (j['reviews'] ?? 0).toInt(),
        isFeatured: j['isFeatured'] ?? false,
        slug: j['slug'],
      );

  int get discount =>
      originalPrice > price ? ((originalPrice - price) / originalPrice * 100).round() : 0;
}

// All packages from ylootrips.com — shown offline, API merges on top
final List<TourPackage> demoPackages = [
  // ── Domestic Treks & Hill Stations ─────────────────────────────────────────
  TourPackage(id: 'dom-001', title: 'Auli Snow Package from Delhi', destination: 'Auli, Uttarakhand',
    description: 'Snow sports, scenic cable car rides and panoramic Himalayan views in Auli, Uttarakhand.',
    imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80',
    price: 6999, originalPrice: 7349, nights: 4, days: 5, category: 'adventure',
    highlights: ["Asia's longest cable car", 'Views of Nanda Devi', 'Gorson Bugyal trek', 'Optional snow skiing'],
    rating: 4.8, reviews: 312, isFeatured: true, badge: 'Winter Favourite', slug: 'auli-package-from-delhi'),
  TourPackage(id: 'dom-002', title: 'Jibhi Tirthan Valley Trip', destination: 'Jibhi, Himachal Pradesh',
    description: 'Hidden gem of Himachal — serene valleys, waterfalls and Bollywood movie locations.',
    imageUrl: 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=800&q=80',
    price: 6999, originalPrice: 7349, nights: 4, days: 5, category: 'domestic',
    highlights: ['Jalori Pass at 10,800 ft', 'Sarolsar Lake trek', 'Jibhi Waterfall & Thailand Pool', 'YJHD filming location'],
    rating: 4.7, reviews: 198, isFeatured: true, badge: 'Hidden Gem', slug: 'jibhi-tirthan-valley-trip'),
  TourPackage(id: 'dom-003', title: 'Manali, Solang & Kasol Tour', destination: 'Manali + Kasol, Himachal Pradesh',
    description: 'Best of Himachal — snow peaks, river valleys, apple orchards and the hippie haven of Kasol.',
    imageUrl: 'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?w=800&q=80',
    price: 6500, originalPrice: 6999, nights: 4, days: 5, category: 'domestic',
    highlights: ['Solang Valley adventures', 'Atal Tunnel & Sissu', 'Hidimba Temple, Old Manali', 'Kasol & Manikaran Sahib'],
    rating: 4.8, reviews: 521, isFeatured: true, badge: 'Best Seller', slug: 'manali-solang-kasol-tour'),
  TourPackage(id: 'dom-004', title: 'Kedarnath Yatra from Delhi', destination: 'Kedarnath, Uttarakhand',
    description: 'Sacred pilgrimage to one of the 12 Jyotirlingas at 11,755 ft above sea level.',
    imageUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80',
    price: 7999, originalPrice: 8399, nights: 4, days: 5, category: 'domestic',
    highlights: ['One of 12 Jyotirlingas', '16 km trek Gaurikund → Kedarnath', 'Devprayag confluence', 'Route via Haridwar & Rishikesh'],
    rating: 4.9, reviews: 476, isFeatured: true, badge: 'Pilgrimage', slug: 'kedarnath-yatra-from-delhi'),
  TourPackage(id: 'dom-005', title: 'Lakshadweep Island Tour', destination: 'Agatti & Bangaram Islands, Lakshadweep',
    description: 'Untouched coral islands, turquoise lagoons and some of India\'s best snorkelling spots.',
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
    price: 22000, originalPrice: 23100, nights: 4, days: 5, category: 'beach',
    highlights: ['Snorkeling, scuba & kayaking', 'Bangaram Island dolphins & turtles', 'Glass boat rides & island hopping', 'Thinnakara Island sandbank'],
    rating: 4.9, reviews: 167, isFeatured: true, badge: 'Luxury Pick', slug: 'lakshadweep-tour-from-mumbai'),
  TourPackage(id: 'dom-006', title: 'Coorg Weekend Tour from Bangalore', destination: 'Coorg (Kodagu), Karnataka',
    description: 'Coffee estates, waterfalls, elephant interactions and a peaceful mountain escape from Bangalore.',
    imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80',
    price: 3287, originalPrice: 3499, nights: 2, days: 3, category: 'domestic',
    highlights: ['Mandalpatti Viewpoint', 'Abbey Falls', "Raja's Seat sunset", 'Elephant interaction'],
    rating: 4.6, reviews: 289, isFeatured: false, badge: 'Weekend Escape', slug: 'coorg-tour-from-bangalore'),
  TourPackage(id: 'dom-007', title: 'Winter Spiti Valley Tour', destination: 'Spiti Valley, Himachal Pradesh',
    description: 'The cold desert of Himachal — ancient monasteries, wild landscapes and an epic adventure.',
    imageUrl: 'https://images.unsplash.com/photo-1533130061792-64b345e4a833?w=800&q=80',
    price: 14999, originalPrice: 15749, nights: 7, days: 8, category: 'adventure',
    highlights: ["World's highest suspension bridge (Chicham)", "World's highest post office (Hikkim)", 'Key & Tabo Monasteries', "Chitkul — India's last village"],
    rating: 4.9, reviews: 143, isFeatured: false, badge: 'Epic Journey', slug: 'spiti-valley-winter-tour'),
  TourPackage(id: 'dom-008', title: 'Chopta Tungnath & Chandrashila Trek', destination: 'Chopta, Uttarakhand',
    description: 'The mini Switzerland of Uttarakhand — highest Shiva temple trek with panoramic Himalayan views.',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    price: 4899, originalPrice: 5199, nights: 2, days: 3, category: 'adventure',
    highlights: ['Tungnath Temple (highest Shiva temple)', 'Chandrashila Peak at 13,000 ft', 'Deoriatal Lake panoramic views', 'Beginner-friendly weekend trek'],
    rating: 4.8, reviews: 387, isFeatured: false, badge: 'Best Seller', slug: 'chopta-tungnath-chandrashila-trek'),
  TourPackage(id: 'dom-009', title: 'Kedarkantha Trek', destination: 'Sankri, Uttarkashi, Uttarakhand',
    description: 'One of the finest winter treks in India with stunning 360° snow panoramas at the summit.',
    imageUrl: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=800&q=80',
    price: 4499, originalPrice: 4799, nights: 4, days: 5, category: 'adventure',
    highlights: ['360° views at 12,500 ft', 'Juda Ka Talab frozen lake camping', 'Kalanag & Swargarohini peak views', 'Dense rhododendron & oak forests'],
    rating: 4.9, reviews: 562, isFeatured: false, badge: 'Winter Trek', slug: 'kedarkantha-trek'),
  TourPackage(id: 'dom-010', title: 'Kheerganga Trek with Camping', destination: 'Kasol, Himachal Pradesh',
    description: 'A gentle trek through lush Parvati Valley to hot springs and panoramic meadows.',
    imageUrl: 'https://images.unsplash.com/photo-1517760444937-f6397edcbbcd?w=800&q=80',
    price: 1150, originalPrice: 1299, nights: 1, days: 2, category: 'adventure',
    highlights: ['Natural hot water springs at Kheerganga', 'Ideal first-timer trek (18 km round trip)', 'Apple orchards & pine forest trail', 'Bonfire & music sessions'],
    rating: 4.6, reviews: 734, isFeatured: false, badge: 'Budget Pick', slug: 'kheerganga-trek-camping'),
  TourPackage(id: 'dom-011', title: 'Dayara Bugyal Trek', destination: 'Raithal, Uttarakhand',
    description: "One of India's finest alpine meadows at 12,000 ft — a paradise in both summer and winter.",
    imageUrl: 'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?w=800&q=80',
    price: 5299, originalPrice: 5599, nights: 3, days: 4, category: 'adventure',
    highlights: ["28 sq km meadow — India's finest", 'Best winter trek in Himalayas', 'Panoramic Himalayan views', 'Beginner-friendly; year-round'],
    rating: 4.7, reviews: 298, isFeatured: false, badge: 'Alpine Meadow', slug: 'dayara-bugyal-trek'),
  TourPackage(id: 'dom-012', title: 'Nag Tibba Trek', destination: 'Dehradun, Uttarakhand',
    description: 'The highest peak of the Lower Himalayas — closest high-altitude weekend trek from Delhi.',
    imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80',
    price: 1499, originalPrice: 1599, nights: 1, days: 2, category: 'adventure',
    highlights: ['Summit at 9,915 ft — closest high trek from Delhi', 'Kedarnath & Chaukamba peak views', 'Rhododendron & deodar forests', 'Ideal weekend getaway'],
    rating: 4.6, reviews: 612, isFeatured: false, badge: 'Weekend Trek', slug: 'nag-tibba-trek'),
  TourPackage(id: 'dom-013', title: 'Hampta Pass Trek + Chandratal Lake', destination: 'Manali, Himachal Pradesh',
    description: 'Cross from green Kullu Valley to the barren Lahaul landscape via Hampta Pass.',
    imageUrl: 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?w=800&q=80',
    price: 6999, originalPrice: 7349, nights: 4, days: 5, category: 'adventure',
    highlights: ['Cross Hampta Pass at 14,039 ft', 'Chandratal Lake at 14,100 ft', '4 nights camping', 'Oxygen cylinders & first aid'],
    rating: 4.8, reviews: 276, isFeatured: false, badge: 'Moderate Trek', slug: 'hampta-pass-trek-chandratal'),
  TourPackage(id: 'dom-014', title: 'Sar Pass Trek', destination: 'Kasol, Himachal Pradesh',
    description: 'A classic Himalayan crossover through pine forests, open meadows, and snowfields.',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    price: 5899, originalPrice: 6299, nights: 4, days: 5, category: 'adventure',
    highlights: ['Cross Sar Pass at 13,799 ft', 'Frozen lakes & snow-capped Parvati Valley', '48 km total trekking', 'Shoes & safety gear included'],
    rating: 4.7, reviews: 341, isFeatured: false, badge: 'Moderate Trek', slug: 'sar-pass-trek'),
  TourPackage(id: 'dom-015', title: 'Prashar Lake Trek & Camping', destination: 'Mandi, Himachal Pradesh',
    description: 'Sacred lake at 8,900 ft with a floating island and breathtaking 360° Himalayan panoramas.',
    imageUrl: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=800&q=80',
    price: 2640, originalPrice: 2799, nights: 1, days: 2, category: 'domestic',
    highlights: ['Sacred Prashar Lake at 8,900 ft', '360° Himalayan panoramic views', 'Sunrise & sunset at the lake', 'Suitable for beginners'],
    rating: 4.6, reviews: 223, isFeatured: false, badge: 'Easy Trek', slug: 'prashar-lake-trek-camping'),
  TourPackage(id: 'dom-016', title: 'Har Ki Dun Trek with Camping', destination: 'Sankri, Uttarakhand',
    description: 'Trek to the Valley of Gods — glacial landscapes, ancient villages and Himalayan wildlife.',
    imageUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80',
    price: 7999, originalPrice: 8399, nights: 6, days: 7, category: 'adventure',
    highlights: ['Glacial valley at 11,800 ft', 'Swargarohini & Black Peak views', 'Mahabharata-era villages', 'Winter & summer accessible'],
    rating: 4.8, reviews: 189, isFeatured: false, badge: 'Moderate Trek', slug: 'har-ki-dun-trek'),
  TourPackage(id: 'dom-017', title: 'Roopkund Trek', destination: 'Lohajung, Uttarakhand',
    description: "India's most iconic high-altitude trek to a mystery lake at 16,499 ft with skeletal remains.",
    imageUrl: 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?w=800&q=80',
    price: 11999, originalPrice: 12599, nights: 7, days: 8, category: 'adventure',
    highlights: ['Mystery Lake at 16,499 ft', '~200 preserved 9th-century skeletal remains', 'Ali & Bedni Bugyal meadows', "India's most iconic high-altitude trek"],
    rating: 4.9, reviews: 254, isFeatured: false, badge: 'Difficult Trek', slug: 'roopkund-trek'),
  TourPackage(id: 'dom-018', title: 'Chadar Trek — Frozen Zanskar River', destination: 'Zanskar, Ladakh',
    description: 'Walk on the frozen Zanskar River — one of the most extraordinary treks on earth.',
    imageUrl: 'https://images.unsplash.com/photo-1533130061792-64b345e4a833?w=800&q=80',
    price: 14999, originalPrice: 15999, nights: 8, days: 9, category: 'adventure',
    highlights: ['Trek on frozen river at -20°C', 'Caves & gorges of Zanskar', 'Nomad village homestays', 'Unique winter-only experience'],
    rating: 4.9, reviews: 212, isFeatured: false, badge: 'Extreme Trek', slug: 'chadar-trek-frozen-zanskar'),
  // ── International & Featured ────────────────────────────────────────────────
  TourPackage(id: 'int-001', title: 'Bali Honeymoon Package', destination: 'Bali, Indonesia',
    description: 'Romance in paradise — rice terraces, temples, luxury villas and pristine beaches.',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    price: 52499, originalPrice: 65999, nights: 6, days: 7, category: 'honeymoon',
    highlights: ['Ubud Rice Terraces', 'Tanah Lot Temple', 'Private Villa', 'Seminyak Beach'],
    rating: 4.9, reviews: 312, isFeatured: true, badge: 'Honeymoon', slug: 'bali-honeymoon-package'),
  TourPackage(id: 'int-002', title: 'Kashmir Paradise Tour', destination: 'Srinagar, Kashmir',
    description: 'Shikara rides on Dal Lake, meadows of Pahalgam, and snow-capped Gulmarg.',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    price: 18999, originalPrice: 24999, nights: 6, days: 7, category: 'domestic',
    highlights: ['Dal Lake Shikara', 'Gulmarg Gondola', 'Pahalgam Valley', 'Mughal Gardens'],
    rating: 4.9, reviews: 428, isFeatured: true, badge: 'Trending', slug: 'kashmir-tour-package'),
  TourPackage(id: 'int-003', title: 'Dubai Luxury Escape', destination: 'Dubai, UAE',
    description: 'Iconic skyline, desert safaris, gold souks and world-class luxury shopping.',
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
    price: 45999, originalPrice: 57999, nights: 5, days: 6, category: 'international',
    highlights: ['Burj Khalifa', 'Desert Safari', 'Dubai Mall', 'Gold Souk'],
    rating: 4.8, reviews: 289, isFeatured: true, badge: 'Luxury', slug: 'dubai-tour-package-from-delhi'),
  TourPackage(id: 'int-004', title: 'Kerala Backwaters & Beaches', destination: 'Kerala, India',
    description: 'Houseboat stays on serene backwaters, lush tea estates, and golden beaches.',
    imageUrl: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    price: 22499, originalPrice: 28999, nights: 7, days: 8, category: 'domestic',
    highlights: ['Houseboat Stay', 'Munnar Tea Gardens', 'Kathakali Show', 'Alleppey Canals'],
    rating: 4.8, reviews: 356, isFeatured: true, badge: 'Best Value', slug: 'kerala-tour-package'),
  TourPackage(id: 'int-005', title: 'Maldives Luxury Package', destination: 'Maldives',
    description: 'Overwater bungalows, crystal-clear lagoons and stunning coral reefs.',
    imageUrl: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80',
    price: 89999, originalPrice: 115000, nights: 5, days: 6, category: 'international',
    highlights: ['Overwater Villa', 'Snorkelling', 'Dolphin Cruise', 'Spa Retreat'],
    rating: 4.9, reviews: 198, isFeatured: true, badge: 'Premium', slug: 'maldives-luxury-package'),
  TourPackage(id: 'int-006', title: 'Goa Beach Holiday', destination: 'Goa, India',
    description: 'Sun, sand, Portuguese churches and the most vibrant beach culture in India.',
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
    price: 12999, originalPrice: 16999, nights: 4, days: 5, category: 'beach',
    highlights: ['Baga Beach', 'Old Goa Churches', 'Water Sports', 'Flea Markets'],
    rating: 4.7, reviews: 512, isFeatured: true, badge: 'Beach', slug: 'goa-tour-package'),
  TourPackage(id: 'int-007', title: '10-Day Golden Triangle', destination: 'Delhi · Agra · Jaipur',
    description: "India's iconic heritage trail — Taj Mahal, Amber Fort, and Old Delhi in one grand journey.",
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80',
    price: 117600, originalPrice: 147000, nights: 9, days: 10, category: 'heritage',
    highlights: ['Taj Mahal Sunrise', 'Amber Fort', 'Old Delhi Tour', 'Qutub Minar'],
    rating: 4.9, reviews: 312, isFeatured: true, badge: 'Most Popular', slug: 'golden-triangle-10-day'),
  TourPackage(id: 'int-008', title: '7-Day Rajasthan Heritage', destination: 'Jaipur · Jodhpur · Udaipur',
    description: 'Royal palaces, desert safaris, lake-side palaces and the Blue City in one week.',
    imageUrl: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=800&q=80',
    price: 79600, originalPrice: 99500, nights: 6, days: 7, category: 'heritage',
    highlights: ['Desert Safari', 'Lake Palace', 'Blue City', 'Hawa Mahal'],
    rating: 4.8, reviews: 194, isFeatured: false, badge: 'Quick Escape', slug: 'rajasthan-heritage-7-day'),
  TourPackage(id: 'int-009', title: 'Andaman Island Escape', destination: 'Port Blair · Havelock · Neil Island',
    description: 'Crystal-clear waters, coral reefs, and pristine beaches of the Andaman Sea.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    price: 32999, originalPrice: 42000, nights: 5, days: 6, category: 'beach',
    highlights: ['Radhanagar Beach', 'Scuba Diving', 'Coral Reefs', 'Elephant Beach'],
    rating: 4.8, reviews: 276, isFeatured: false, badge: 'Beach', slug: 'andaman-tour-package'),
  TourPackage(id: 'int-010', title: 'Ladakh High Altitude Trek', destination: 'Leh · Nubra · Pangong',
    description: 'Monasteries, sand dunes, and the highest motorable road in the world.',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    price: 28999, originalPrice: 38000, nights: 7, days: 8, category: 'adventure',
    highlights: ['Pangong Lake', 'Nubra Valley', 'Khardung La', 'Hemis Monastery'],
    rating: 4.9, reviews: 318, isFeatured: false, badge: 'Adventure', slug: 'ladakh-tour-package'),
  TourPackage(id: 'int-011', title: 'Thailand Beach & Culture', destination: 'Bangkok · Phuket · Krabi',
    description: 'Street food, temples, emerald-green islands and world-famous nightlife.',
    imageUrl: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80',
    price: 38999, originalPrice: 48999, nights: 6, days: 7, category: 'international',
    highlights: ['Phi Phi Islands', 'Grand Palace', 'Street Food Tour', 'Elephant Sanctuary'],
    rating: 4.7, reviews: 423, isFeatured: false, badge: 'International', slug: 'thailand-tour-package'),
  TourPackage(id: 'int-012', title: 'Singapore City Break', destination: 'Singapore',
    description: 'Gardens by the Bay, Marina Bay Sands, Sentosa Island and hawker food paradise.',
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80',
    price: 42999, originalPrice: 54999, nights: 5, days: 6, category: 'international',
    highlights: ['Gardens by the Bay', 'Sentosa Island', 'Universal Studios', 'Clarke Quay'],
    rating: 4.8, reviews: 267, isFeatured: false, badge: 'International', slug: 'singapore-tour-package'),
  TourPackage(id: 'int-013', title: 'Varanasi Spiritual Journey', destination: 'Varanasi · Sarnath · Prayagraj',
    description: 'Ganga Aarti, ancient ghats, and the spiritual heart of India.',
    imageUrl: 'https://images.unsplash.com/photo-1561361058-c24e01b5e367?w=800&q=80',
    price: 11999, originalPrice: 14999, nights: 3, days: 4, category: 'heritage',
    highlights: ['Ganga Aarti', 'Boat Ride', 'Sarnath', 'Ancient Ghats'],
    rating: 4.7, reviews: 389, isFeatured: false, badge: 'Cultural', slug: 'varanasi-tour-package'),
  TourPackage(id: 'int-014', title: 'Manali Snow Adventure', destination: 'Manali · Solang · Rohtang',
    description: 'Snow sports, river rafting, and mountain trails in the Kullu Valley.',
    imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80',
    price: 12999, originalPrice: 16999, nights: 4, days: 5, category: 'domestic',
    highlights: ['Rohtang Pass', 'Solang Valley', 'River Rafting', 'Paragliding'],
    rating: 4.8, reviews: 441, isFeatured: false, badge: 'Adventure', slug: 'manali-tour-package'),
  TourPackage(id: 'int-015', title: '14-Day Kerala & South India', destination: 'Kochi · Munnar · Alleppey · Pondicherry',
    description: 'A deep dive into South India — backwaters, spice estates, French Quarter and temple towns.',
    imageUrl: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    price: 159600, originalPrice: 199500, nights: 13, days: 14, category: 'domestic',
    highlights: ['Houseboat Stay', 'Tea Estates', 'French Quarter', 'Meenakshi Temple'],
    rating: 4.9, reviews: 287, isFeatured: false, badge: 'Best Value', slug: 'kerala-south-india-14-day'),
  TourPackage(id: 'int-016', title: 'Coorg Coffee Estate Retreat', destination: 'Coorg · Mysore · Wayanad',
    description: 'Rolling coffee plantations, spice trails, and the perfume of the Western Ghats.',
    imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80',
    price: 13999, originalPrice: 17999, nights: 3, days: 4, category: 'domestic',
    highlights: ['Coffee Plantation', 'Abbey Falls', 'Nagarhole Wildlife', 'Spice Tour'],
    rating: 4.6, reviews: 203, isFeatured: false, badge: 'Nature', slug: 'coorg-tour-package'),
];
